baseurl = ""
metaDataFormat = "yaml"
title = "Diskominfo Provinsi Kalimantan Barat"
theme = "blist"
DefaultContentLanguage = "id"
DefaultContentLanguageInSubdir = false
contentDir = "content" #English"
weight = 1
languageName = "Indonesia"

[languages.id.params]
introTitle = "Dinas Komunikasi dan Informatika"
introSubtitle = "Website resmi Dinas Komunikasi dan Informatika provinsi Kalimantan Barat"
introPhoto = "/picture.jpg"
logo = "/logo.png"
name = "Top Post"
url = "/en/blog/emoji-support/"
weight = 4
[params]
domain = 'diskominfo.kalbarprov.go.id'
phone = "628152076444"
address = "Jalan Ahmad Yani Gedung Pelayanan Terpadu Lt. 6, Kalimantan Barat 78124"
email = "diskominfo@kalbarprov.go.id"
darkModeToggle = true
enableSearch = true
searchKeys = "["
copyright = "Copyright ©2024"
favicon = "/favicon.svg"
ascentColor = "bg-defaultColor"
frontBundle1 = "aplikasi-pusat"
frontBundle2 = "layanan"
frontBundle3 = "aplikasi-daerah"
frontBundle4 = "website-terkait"
frontBundle5 = "formulir"
frontBundle6 = "berita"
frontBundle7 = "foto"
frontBundle8 = "galeri-video"
hideMeta = false
hideOtherLanguages = false
toc = true
hidePageThumbnail = false
introTitle = "Dinas Komunikasi dan Informatika"
introSubtitle = "Website resmi Dinas Komunikasi dan Informatika provinsi Kalimantan Barat"
[params.comments]
system = "giscus"
repo = ""
repoid = ""
category = ""
categoryid = ""
mapping = ""
strict = ""
reactionsenabled = ""
emitmetadata = ""
inputposition = ""
theme = ""
[params.homepage.social]
title = "Follow me"
description = "I work on everything coding and tweet developer memes"
[build]
writeStats = true
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
unsafe = true

[[languages.id.menu.main]]
identifier = 'beranda'
name = "Beranda"
url = "/"
weight = 1
[[languages.id.menu.main]]
identifier = 'tentang-kami'
name = "Tentang Kami"
url = "/tentang-kami"
weight = 2
[[languages.id.menu.main]]
identifier = 'informasi'
name = "Informasi"
url = "/informasi"
weight = 3
[[languages.id.menu.main]]
identifier = 'berita'
name = "Berita"
url = "/berita"
weight = 4
[[languages.id.menu.main]]
identifier = 'ppid'
name = "PPID"
url = "/ppid"
weight = 5
[[languages.id.menu.main]]
identifier = 'csirt'
name = "CSIRT"
url = "/csirt"
weight = 6


[[params.homepage.social.icons]]
website = "twitter"
url = "https://x.com/KominfoKalbar"
[[params.homepage.social.icons]]
website = "tiktok"
url = "https://www.tiktok.com/@diskominfo.kalbar"
[[params.homepage.social.icons]]
website = "youtube"
url = "https://www.youtube.com/@DiskominfoProvKalbar"
[[params.homepage.social.icons]]
website = "instagram"
url = "https://www.instagram.com/diskominfo.kalbar/"
[[params.homepage.social.icons]]
website = "facebook"
url = "https://www.facebook.com/Diskominfoprovkalbar"

[[params.agenda]]
lokasi = "Ruang AUVI"
jamMulai = "08:30"
jamSelesai = "12:00"
judul = "undangan pembahasan rencana kerja sama, Sekretaris Daerah/RO-PEM, Jumat, 2 agustus 2024, di Ruang AUVI"
hari = "Jumat"

[[params.agenda]]
lokasi = "Ruang Rapat Wakil Gubernur"
jamMulai = "13:30"
jamSelesai = "16:00"
judul = "undangan pembahasan persiapan peringatan HUT RI ke 79, Sekretaris Daerah, Jum'at 2 Agustus 2024, 13.30, RR Wakil Gubernur"
hari = "Jumat"

[[params.agenda]]
lokasi = "Balai Petitih"
jamMulai = "13:30"
jamSelesai = "15:45"
judul = "Mendengarkan Pidato Presiden RI pada Penyampaian RUU APBN Tahun 2024 oleh Biro Pemerintahan"
hari = "Jumat"

[[params.agenda]]
lokasi = "Balai Petitih"
jamMulai = "13:30"
jamSelesai = "15:45"
judul = "Gladi pengukuhan Paskibraka Pemprov Kalbar"
hari = "Kamis"

[[params.agenda]]
lokasi = "DAR"
jamMulai = "09:00"
jamSelesai = "12:00"
judul = "Zoom meeting Diskusi Daerah Perbatasan dengan PJ Gubernur Kalbar oleh pusat riset politik BRIN"
hari = "Kamis"

[[params.sliders.images]]
url = "slider1.png"
extension = "png"


[[params.sliders.images]]
url = "slider2.png"
extension = "png"


[[params.sliders.images]]
url = "slider3.png"
extension = "png"

[[params.sliders.images]]
url = "slider3.png"
extension = "png"

[[params.sliders.images]]
url = "slider4.png"
extension = "png"

[[params.sliders.images]]
url = "slider5.png"
extension = "png"




