

baseurl = ""
metaDataFormat = "yaml"
title = "Situs Resmi Dinas Komunikasi dan Informatika Kalbar"
theme = "newdiskominfo"
DefaultContentLanguage = "id"
DefaultContentLanguageInSubdir = false
contentDir = "content" #English"
weight = 1
languageName = "Indonesia"
[languages.id.params]
introTitle = "Dinas Komunikasi dan Informatika"
introSubtitle = "Website resmi Dinas Komunikasi dan Informatika provinsi Kalimantan Barat"
introPhoto = "/picture.jpg"
logo = "/logo.png"
name = "Top Post"
url = "/en/blog/emoji-support/"
weight = 4
[params]
domain = 'diskominfo.kalbarprov.go.id'
homeVideo = "1PCYZTA9FeU"
phone = "628152076444"
address = "Jalan Ahmad Yani Gedung Pelayanan Terpadu Lt. 6, Kalimantan Barat 78124"
email = "diskominfo@kalbarprov.go.id"
darkModeToggle = true
enableSearch = true
searchKeys = "["
copyright = "Copyright ©2023"
favicon = "/favicon.svg"
ascentColor = "bg-defaultColor"
frontBundle = "Form Informasi"
frontBundle2 = ""
frontBundle3 = "Layanan"
frontBundle4 = "Link Terkait"
frontBundle5 = "Agenda"
frontBundle6 = "Social Media"
frontBundle7 = "FAQ"
frontBundle8 = "Kontak Kami"
hideMeta = false
hideOtherLanguages = false
toc = true
hidePageThumbnail = false
introTitle = "Dinas Komunikasi dan Informatika"
introSubtitle = "Website resmi Dinas Komunikasi dan Informatika provinsi Kalimantan Barat"
[params.comments]
system = "giscus"
repo = ""
repoid = ""
category = ""
categoryid = ""
mapping = ""
strict = ""
reactionsenabled = ""
emitmetadata = ""
inputposition = ""
theme = ""
[params.homepage.social]
title = "Follow me"
description = "I work on everything coding and tweet developer memes"
[build]
writeStats = true
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
unsafe = true


[[params.kontakKami.subjek]]
nama = "Kerjasama"

[[params.kontakKami.subjek]]
nama = "Konten"

[[params.kontakKami.subjek]]
nama = "Pengaduan"

[[params.kontakKami.subjek]]
nama = "Lainnya"





[[languages.id.menu.main]]
identifier = 'profil'
name = "Profil"
url = "/profil"
weight = 1



[[languages.id.menu.main]]
identifier = 'sop'
name = "SOP"
url = "/sop"
weight = 3



[[params.agenda]]
lokasi = "Ruang AUVI"
jamMulai = "08:30"
jamSelesai = "12:00"
judul = "undangan pembahasan rencana kerja sama, Sekretaris Daerah/RO-PEM, Jumat, 2 agustus 2024, di Ruang AUVI"
tanggal = "02/08/2024"
hari = "Jumat"

[[params.agenda]]
lokasi = "Ruang Rapat Wakil Gubernur"
jamMulai = "13:30"
jamSelesai = "16:00"
judul = "undangan pembahasan persiapan peringatan HUT RI ke 79, Sekretaris Daerah, Jum'at 2 Agustus 2024, 13.30, RR Wakil Gubernur"
tanggal = "02/08/2024"
hari = "Jumat"

[[params.agenda]]
lokasi = "Balai Petitih"
jamMulai = "13:30"
jamSelesai = "15:45"
judul = "Mendengarkan Pidato Presiden RI pada Penyampaian RUU APBN Tahun 2024 oleh Biro Pemerintahan"
tanggal = "16/08/2024"
hari = "Jumat"

[[params.agenda]]
lokasi = "Balai Petitih"
jamMulai = "13:30"
jamSelesai = "15:45"
judul = "Gladi pengukuhan Paskibraka Pemprov Kalbar"
tanggal = "15/08/2024"
hari = "Kamis"

[[params.agenda]]
lokasi = "DAR"
jamMulai = "09:00"
jamSelesai = "12:00"
judul = "Zoom meeting Diskusi Daerah Perbatasan dengan PJ Gubernur Kalbar oleh pusat riset politik BRIN"
tanggal = "15/08/2024"
hari = "Kamis"




[[params.sliders.images]]
url = "1.png"
extension = "png"


[[params.sliders.images]]
url = "Kantor Gub.jpg"
extension = "jpg"


[[params.sliders.images]]
url = "WhatsApp Image 2024-08-14 at 10.10.35_4dc238b5.jpg"
extension = "jpg"
